name: batch-docker-conda
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - pillow=7.1.2
  - scikit-image=0.18.3
  - numpy=1.20.0
  - nomkl=2.0
  - mxnet-mkl=1.5.0
  - boto3=1.19.11
